name: phase5_project
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  path_provider_foundation: ^2.0.0
  jwt_decoder: ^2.0.1
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  http:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/qr_code.jpg
    - assets/images/No Type Part III.JPEG
    - assets/images/Brunch Party.jpg
    - assets/images/1 Motif Party.jpeg
    - assets/images/Familiar Faces.jpg
    - assets/images/First Thursdays.png
    - assets/images/BK Block Party.jpg
    - assets/images/A NY Juneteenth.jpg
    - assets/images/Bedquin.jpg
    - assets/images/Bladee.jpg
    - assets/images/CMYK.jpg
    - assets/images/Dance Dubs.jpg
    - assets/images/ESG.jpg
    - assets/images/Frequency.jpg
    - assets/images/Lavern.jpg
    - assets/images/Major League.jpg
    - assets/images/No Requests.jpg
    - assets/images/One Night.jpg
    - assets/images/Pride.jpg
    - assets/images/South House.jpg
    - assets/images/X & Ivy.jpg
    - assets/images/Culture Shock.jpg
    - assets/images/Whine Up.jpg
    - assets/images/Versus.jpg
    - assets/images/Sound wav.jpg
    - assets/images/Big Band Jubilee.jpg
    - assets/images/We Outside.jpg
    - assets/images/Harlem Late Night Jazz.jpg
    - assets/images/Summer Jazz Series.jpg
    - assets/images/Jazz Fest Party.jpg
    - assets/images/Juneteenth With Masego.jpg
    - assets/images/More R&B Please.jpg
    - assets/images/Tompkins Ave.jpg
    - assets/images/Elevate Social.jpg
    - assets/images/Juneteenth Block Party.jpg
    - assets/images/Hello Summer The BBQ.jpg
    - assets/images/No Filter.jpg
    - assets/images/Ginja.jpg
    - assets/images/Parks & Rec.jpg
    - assets/images/Suede.jpg
    - assets/images/Bushwick Grand.jpg
    - assets/images/I Heart R&B.jpg
    - assets/images/Beautiful Faces.jpg
    - assets/images/Brown Sugar Bounce.jpg
    - assets/images/Lomiiel Live.jpg
    - assets/images/For The Likes.jpg
    - assets/images/Social Brunch.jpg
    - assets/images/Love From The Sun.jpg
    - assets/images/Nonstop.jpg
    - assets/images/All Night Juana.jpg
    - assets/images/Label Night.jpg
    - assets/images/Nonstop 2.jpg
    - assets/images/Residency Night.jpg
    - assets/images/Groovy Nonstop.jpg
    - assets/images/Likkle Wednesday.jpg
    - assets/images/Yard + Abroad.jpg
    - assets/images/Daft Disko.jpg
    - assets/images/Dolly House.jpg
    - assets/images/Sip Grill & Chill.jpg
    - assets/images/Sip Grill & Chill 2.jpg
    - assets/images/Summer Rockaway Fest.jpg
    - assets/images/Gov Ball.jpg
    - assets/images/Palm Wine Music.jpg
    - assets/images/Gyalifest.jpg
    - assets/images/Circulate Black Dollars.jpg
    - assets/images/DJ BG.png
    - assets/images/Hands up.png
    - assets/images/EP.jpeg

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
