# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_installation_path
  if File.exist?("../.ios/Flutter/engine")
    "../.ios/Flutter/engine"
  else
    File.join(ENV['FLUTTER_ROOT'], "bin", "cache", "artifacts", "engine", "ios")
  end
end

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'ios', 'Flutter', 'Generated.xcconfig'))
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure \"flutter build ios\" is run first"
  end
  File.dirname(generated_xcode_build_settings_path)
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end

  # Add additional pods here if needed
end

flutter_post_install_all_ios_pods File.dirname(File.realpath(__FILE__))
